name: focus
description: "專注番茄 - 結合AI智慧任務拆解的番茄工作法應用程式"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  material_symbols_icons: 4.2867.0

  # Material Design Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.3.0
  
  # Local Storage  
  sqflite: ^2.4.1
  shared_preferences: ^2.3.4
  
  # Network
  dio: ^5.7.0
  
  # Background Services & Notifications
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.10
  workmanager: ^0.5.2
  
  # Audio
  audioplayers: ^6.1.0
  
  # Charts & Data Visualization
  fl_chart: ^0.70.1
  
  # Animations
  lottie: ^3.2.0
  
  # Date & Time
  intl: ^0.19.0
  
  # UI Components
  smooth_page_indicator: ^1.2.0
  
  # Utilities
  uuid: ^4.5.1
  path_provider: ^2.1.5
  
  # Material 3 Dynamic Color Support
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
